name: mooTagify
author: D_mitar
category: Interface
current: 2.0.1
tags: [tags, autocomplete]
docs: https://github.com/DimitarChristoff/mooTagify
demo: http://fragged.org/mooTagify/Demo/index-bootstrap.html
sources:
  - "Source/js/mootagify.js"