name: mooTagify
author: D_mitar
category: Interface
current: 1.2
tags: [tags, autocomplete]
docs: https://github.com/DimitarChristoff/mooTagify
demo: http://fragged.org/mooTagify/Demo/
sources:
  - "Source/js/mootagify.js"