name: mooTagify
author: D_mitar
category: Interface
current: v2.0.3
tags: [tags, autocomplete]
docs: https://github.com/DimitarChristoff/mooTagify
demo: http://fragged.org/mooTagify/Demo/index-bootstrap.html
sources:
  - "Source/js/mootagify.js"